voting: # Frontend
  image: ditmc/voting:step1
  links:
    - redis
  ports:
    - "5000:80"

worker: # Vote processor
  image: ditmc/worker:step1
  links:
    - redis
    - db

result: # Results
  image: ditmc/result:step1
  links:
    - db
  ports:
    - "5001:80"

redis: # Queue
  image: redis

db: # Database
  image: postgres:9.4
