voting-app: # Frontend
  image: ditmc/voting
  ports:
    - "5000:80"

worker: # Vote processor
  image: ditmc/worker

result-app: # Results
  image: ditmc/result
  ports:
    - "5001:80"

redis: # Queue
  image: redis

db: # Database
  image: postgres:9.4
  volumes:
    - "myvolume:/var/lib/postgresql/data"
