voting: # Frontend
  image: ditmc/voting
  links:
    - redis
  ports:
    - "5000:80"

worker: # Vote processor
  image: ditmc/worker
  links:
    - redis
    - db

result: # Results
  image: ditmc/result
  links:
    - db
  ports:
    - "5001:80"

redis: # Queue
  image: redis

db: # Database
  image: postgres:9.4
  volumes:
    - "myvolume:/var/lib/postgresql/data"
